"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in ("1", "true", "yes", "on")


def env_list(name, default=""):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure--5)p!nj-p8f*f1ifw-$o&&cs#5oef!sva)^423t^mrv$1)(+u-",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", default="localhost,127.0.0.1")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "core",
    "users",
    "posts",
    "requests_app",
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# 基本設計書 4章: DBはMySQL。日時カラムはUSE_TZ = TrueのままUTCのnaive datetimeとして保存する

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("DB_NAME", "pen_and_palette"),
        "USER": os.environ.get("DB_USER", "pen_and_palette"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "pen_and_palette"),
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/
# Django/DRF標準のバリデーションメッセージ（必須項目未入力、パスワード強度等）を日本語で
# 返すため"ja"にする（LocaleMiddlewareは使わず、常にこの言語で固定する単一言語アプリのため）

LANGUAGE_CODE = "ja"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


# Django REST Framework
# 基本設計書 3章: Cookie経由のJWT認証。5章: バリデーションエラーは{"フィールド名": [...]}、
# 401/403/404は{"detail": "..."}というDRF標準のエラー形式に従う

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "common.authentication.CookieJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# djangorestframework-simplejwt
# 基本設計書 3章: アクセストークンはsimplejwtで発行するJWT（有効期限15分）。
# リフレッシュトークンはJWTではなく独自のopaqueトークン+DBテーブル（users.models.RefreshToken）
# で管理するため、simplejwt自体のリフレッシュ・ブラックリスト機能は使わない

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "AUTH_COOKIE": "access_token",
}

AUTH_REFRESH_TOKEN_LIFETIME = timedelta(days=14)

# HttpOnly Cookieのsecure属性。本番（DEBUG=False・HTTPS）では自動的にTrueになり、
# ローカル開発（DEBUG=True・HTTP）では自動的にFalseになってCookieが届くようにする
AUTH_COOKIE_SECURE = env_bool("AUTH_COOKIE_SECURE", default=not DEBUG)

# django-cors-headers
# 基本設計書 3.1節: 開発環境はVite(5173)とDjango(8000)の別オリジン間でCookieを送受信するため、
# CORS_ALLOWED_ORIGINSを明示的に許可しCORS_ALLOW_CREDENTIALS = Trueとする

CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", default="http://localhost:5173")
CORS_ALLOW_CREDENTIALS = True

# 画像ストレージ（Amazon S3 / 開発時はMinIO）
# 基本設計書 1〜2章・6.3節: プロキシアップロード方式
# （署名付きURLではなくサーバー経由でS3/MinIOに書き込む）。
# docker-compose.ymlのminioサービスはバケットを匿名read公開しているため、
# querystring_auth=Falseで署名なしの素のURLを生成する。addressing_style="path"は
# MinIOがvirtual-hosted-style（バケット名をホスト名の一部にする）に対応していないため必須
AWS_S3_BUCKET = os.environ.get("AWS_S3_BUCKET", "pen-and-palette-media")
# 本番のAmazon S3では未設定のままにし、boto3のデフォルトエンドポイントを使わせる。
# ローカル開発は.envでMinIOのURLを指定する
AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL") or None
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "minioadmin")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "minioadmin")
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "us-east-1")

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": AWS_S3_BUCKET,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "region_name": AWS_S3_REGION_NAME,
            "addressing_style": "path",
            "querystring_auth": False,
            "file_overwrite": False,
            "default_acl": None,  # MinIOはACL未対応。読み取り公開はminio-init側で設定済み
        },
    },
    "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
}
