"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import json
import os
import urllib.request
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in ("1", "true", "yes", "on")


def env_list(name, default=""):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


def env_int(name, default=0):
    value = os.environ.get(name)
    if value is None or not value.strip():
        return default
    return int(value)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=True)

# SECURITY WARNING: keep the secret key used in production secret!
# 本番（DEBUG=False）はデプロイ側（Secrets Manager等）でDJANGO_SECRET_KEYを必ず注入する。
# 未設定のまま起動させないよう、開発用のフォールバック値は DEBUG=True のときだけ使う。
_DEV_SECRET_KEY = "django-insecure--5)p!nj-p8f*f1ifw-$o&&cs#5oef!sva)^423t^mrv$1)(+u-"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = _DEV_SECRET_KEY
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false.")

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", default="localhost,127.0.0.1")

# ALBのターゲットグループのヘルスチェックは Host: <コンテナのプライベートIP> で届くため、
# ECSのタスクメタデータエンドポイントからそのIPを取得してALLOWED_HOSTSに足す。
# ローカル・CIではECS_CONTAINER_METADATA_URI_V4が無いので何もしない（例外も握りつぶす）。
if not DEBUG and os.environ.get("ECS_CONTAINER_METADATA_URI_V4"):
    try:
        _metadata_url = f"{os.environ['ECS_CONTAINER_METADATA_URI_V4']}/task"
        with urllib.request.urlopen(_metadata_url, timeout=1) as response:
            _task_metadata = json.load(response)
        for _container in _task_metadata.get("Containers", []):
            for _network in _container.get("Networks", []):
                ALLOWED_HOSTS.extend(_network.get("IPv4Addresses", []))
    except Exception:
        # メタデータ取得に失敗しても起動は止めない（ローカル・CIには存在しない）
        pass


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "core",
    "users",
    "posts",
    "requests_app",
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# 本番のみ WhiteNoise で /admin の静的ファイルを gunicorn から直接配信する
# （CDN/Nginx を別途置かずコンテナ単体で完結させる）。開発は runserver の staticfiles
# 配信で足りるうえ、collectstatic 前提の WhiteNoise を挟むと警告が出るため入れない。
# SecurityMiddleware の直後に置くのが WhiteNoise の推奨。
if not DEBUG:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# 基本設計書 4章: DBはMySQL。日時カラムはUSE_TZ = TrueのままUTCのnaive datetimeとして保存する

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("DB_NAME", "pen_and_palette"),
        "USER": os.environ.get("DB_USER", "pen_and_palette"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "pen_and_palette"),
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/
# Django/DRF標準のバリデーションメッセージ（必須項目未入力、パスワード強度等）を日本語で
# 返すため"ja"にする（LocaleMiddlewareは使わず、常にこの言語で固定する単一言語アプリのため）

LANGUAGE_CODE = "ja"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
# このアプリの画面はVue.js（S3+CloudFront配信）で、Django側の静的ファイルは実質的に
# /admin のCSS/JSのみ。本番は Dockerfile で collectstatic し、WhiteNoise で配信する。

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


# Django REST Framework
# 基本設計書 3章: Cookie経由のJWT認証。5章: バリデーションエラーは{"フィールド名": [...]}、
# 401/403/404は{"detail": "..."}というDRF標準のエラー形式に従う

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "common.authentication.CookieJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# djangorestframework-simplejwt
# 基本設計書 3章: アクセストークンはsimplejwtで発行するJWT（有効期限15分）。
# リフレッシュトークンはJWTではなく独自のopaqueトークン+DBテーブル（users.models.RefreshToken）
# で管理するため、simplejwt自体のリフレッシュ・ブラックリスト機能は使わない

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "AUTH_COOKIE": "access_token",
}

AUTH_REFRESH_TOKEN_LIFETIME = timedelta(days=14)

# HttpOnly Cookieのsecure属性。本番（DEBUG=False・HTTPS）では自動的にTrueになり、
# ローカル開発（DEBUG=True・HTTP）では自動的にFalseになってCookieが届くようにする
AUTH_COOKIE_SECURE = env_bool("AUTH_COOKIE_SECURE", default=not DEBUG)

# django-cors-headers
# 基本設計書 3.1節: 開発環境はVite(5173)とDjango(8000)の別オリジン間でCookieを送受信するため、
# CORS_ALLOWED_ORIGINSを明示的に許可しCORS_ALLOW_CREDENTIALS = Trueとする。
# 本番はCloudFrontの単一ディストリビューション（/api/* をALBへ、それ以外をS3へ振り分け）で
# フロントとAPIを同一オリジンに見せるが、ブラウザは状態変化を伴うリクエスト（POST/PUT/DELETE）で
# Originヘッダーを送るため、CloudFrontドメインを許可しておく必要がある。ドメインは apply 後まで
# 確定しないため、完全一致（CORS_ALLOWED_ORIGINS）ではなく正規表現で
# https://*.cloudfront.net を許可する（CORS_ALLOWED_ORIGIN_REGEXES に渡す）。

CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", default="http://localhost:5173")
CORS_ALLOWED_ORIGIN_REGEXES = env_list("CORS_ALLOWED_ORIGIN_REGEXES")
CORS_ALLOW_CREDENTIALS = True

# Django admin を CloudFront ドメイン経由で使うため（API本体は CookieJWTAuthentication のみで
# DRF の CSRF 検証対象外だが、admin のログインフォームには必要）。スキーム付きで指定する。
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

# 本番のセキュリティ設定（DEBUG=Falseのときだけ有効化。個別に環境変数で上書きできる）
if not DEBUG:
    # CloudFront が AllViewer オリジンリクエストポリシーで転送するヘッダー。
    # CloudFront〜ALB間はHTTPだが、これで Django は元リクエストがHTTPSだったと判定できる。
    SECURE_PROXY_SSL_HEADER = ("HTTP_CLOUDFRONT_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", default=True)
    CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", default=True)
    # HTTPSへのリダイレクトは CloudFront 側（viewer_protocol_policy = redirect-to-https）で
    # 済ませる。Django側で行うと、リダイレクトを追わないALBのヘルスチェックが301を
    # 不健全と誤判定するため False 固定にする。
    SECURE_SSL_REDIRECT = False
    # HSTS は既定で無効（0）。*.cloudfront.net は他プロジェクトと共有するドメインのため、
    # includeSubDomains 付きで有効化すると影響範囲が広すぎる。独自ドメイン導入時に見直す。
    SECURE_HSTS_SECONDS = env_int("SECURE_HSTS_SECONDS", default=0)

    # `manage.py check --deploy` の指摘のうち、本構成では意図的に対応しないものを黙らせる。
    # 詳細は docs/infrastructure-design.md 参照。
    #   security.W004 (HSTS未設定): 上記のとおり共有ドメインのため既定で無効
    #   security.W008 (SSL_REDIRECT未設定): CloudFront 側で redirect-to-https 済み
    #   mail.E001: このアプリはメール送信機能を持たない（会員登録にメール確認なし）
    SILENCED_SYSTEM_CHECKS = ["security.W004", "security.W008", "mail.E001"]

# 画像ストレージ（Amazon S3 / 開発時はMinIO）
# 基本設計書 1〜2章・6.3節: プロキシアップロード方式
# （署名付きURLではなくサーバー経由でS3/MinIOに書き込む）。
# docker-compose.ymlのminioサービスはバケットを匿名read公開しているため、
# querystring_auth=Falseで署名なしの素のURLを生成する（本番S3もバケットポリシーで
# 匿名read公開し、同じく署名なしURLをDBに保存する）。addressing_styleは、MinIOが
# virtual-hosted-style（バケット名をホスト名の一部にする）に対応しないため既定"path"。
# 本番S3では"virtual"を環境変数で指定できる。
AWS_S3_BUCKET = os.environ.get("AWS_S3_BUCKET", "pen-and-palette-media")
AWS_S3_ADDRESSING_STYLE = os.environ.get("AWS_S3_ADDRESSING_STYLE", "path")
# 本番のAmazon S3では未設定のままにし、boto3のデフォルトエンドポイントを使わせる。
# ローカル開発は.envでMinIOのURLを指定する
AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL") or None
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "minioadmin")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "minioadmin")
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "us-east-1")

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": AWS_S3_BUCKET,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "region_name": AWS_S3_REGION_NAME,
            "addressing_style": AWS_S3_ADDRESSING_STYLE,
            "querystring_auth": False,
            "file_overwrite": False,
            # MinIO/本番バケットともACLは使わず、匿名read公開はバケットポリシー側で設定する
            "default_acl": None,
        },
    },
    # /admin の静的ファイルを WhiteNoise で圧縮・キャッシュ付き配信する
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# ロギング。LOG_FORMAT=json のとき CloudWatch Logs 向けに1行JSONで出力する。
# それ以外は Django のデフォルト設定（LOGGING未指定）に任せる。
if os.environ.get("LOG_FORMAT") == "json":
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "json": {
                "format": (
                    '{"level": "%(levelname)s", "logger": "%(name)s", '
                    '"time": "%(asctime)s", "message": "%(message)s"}'
                ),
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "json",
            },
        },
        "root": {"handlers": ["console"], "level": "INFO"},
        "loggers": {
            "django": {"handlers": ["console"], "level": "INFO", "propagate": False},
            "gunicorn.error": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }
