# Generated by Django 6.1 on 2026-08-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[("illustration", "イラスト"), ("novel", "小説")],
                default="illustration",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.CheckConstraint(
                condition=models.Q(("post_type__in", ["illustration", "novel"])),
                name="post_type_valid",
            ),
        ),
    ]
