# Generated by Django 6.1 on 2026-08-26 10:40
"""固定の分類タグ12件を投入するデータマイグレーション（基本設計書6.11章）。

利用者による追加・編集・削除ができない固定データのため、モデルを直接importせず
apps.get_model()経由で操作する（将来モデルの定義が変わってもこのマイグレーションの
実行結果が変わらないようにするため）。
"""

from django.db import migrations

TAG_NAMES = [
    "オリジナル",
    "二次創作",
    "ファンタジー",
    "SF",
    "ホラー・ミステリー",
    "恋愛",
    "日常",
    "コメディ",
    "アクション",
    "ドラマ",
    "キャラクターデザイン",
    "風景・背景",
]


def seed_tags(apps, schema_editor):
    Tag = apps.get_model("posts", "Tag")
    Tag.objects.bulk_create(
        [Tag(name=name, display_order=order) for order, name in enumerate(TAG_NAMES)]
    )


def unseed_tags(apps, schema_editor):
    Tag = apps.get_model("posts", "Tag")
    Tag.objects.filter(name__in=TAG_NAMES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_tags"),
    ]

    operations = [
        migrations.RunPython(seed_tags, unseed_tags),
    ]
